export const jobs = [
  {
    id: 'frontend-horizonte',
    title: 'Estágio em Desenvolvimento Front-end',
    company: 'Empresa Horizonte',
    initials: 'EH',
    location: 'São Paulo, SP',
    mode: 'Híbrido',
    type: 'Estágio',
    area: 'Tecnologia',
    salary: 'R$ 1.800,00',
    benefits: ['Vale-refeição', 'Auxílio-transporte', 'Gympass'],
    deadline: '12 de outubro',
    posted: 'Há 2 dias',
    summary: 'Ajude a criar experiências digitais simples e acessíveis para milhares de pessoas.',
    description: 'Você fará parte de um time multidisciplinar e apoiará a evolução de interfaces web, desde a prototipação até a entrega. Procuramos alguém com curiosidade, atenção aos detalhes e vontade de aprender em ciclos curtos.',
    activities: [
      'Desenvolver e ajustar componentes de interface.',
      'Apoiar testes de responsividade e acessibilidade.',
      'Colaborar com design e desenvolvimento nas revisões.',
      'Documentar decisões e aprendizados do projeto.'
    ],
    required: ['HTML semântico', 'CSS responsivo', 'JavaScript básico', 'Git', 'Disponibilidade de 6 horas'],
    desired: ['React', 'Figma', 'Testes de interface'],
    match: 70,
    matched: ['HTML semântico', 'CSS responsivo', 'JavaScript básico', 'Git'],
    gaps: ['Testes de interface', 'Experiência com design systems']
  },
  {
    id: 'dados-orbita',
    title: 'Estágio em Análise de Dados',
    company: 'Órbita Educação',
    initials: 'OE',
    location: 'Remoto — Brasil',
    mode: 'Remoto',
    type: 'Estágio',
    area: 'Dados',
    salary: 'R$ 1.650,00',
    benefits: ['Vale-alimentação', 'Auxílio home office'],
    deadline: '18 de outubro',
    posted: 'Hoje',
    summary: 'Transforme dados educacionais em informações úteis para decisões de produto.',
    description: 'Apoie o time na organização de bases, criação de relatórios e comunicação de descobertas.',
    activities: ['Preparar bases simples.', 'Atualizar dashboards.', 'Documentar análises.'],
    required: ['Excel ou Google Sheets', 'Raciocínio analítico', 'Comunicação escrita'],
    desired: ['SQL', 'Power BI', 'Python'],
    match: 58,
    matched: ['Raciocínio analítico', 'Comunicação escrita'],
    gaps: ['SQL', 'Power BI']
  },
  {
    id: 'ux-aurora',
    title: 'Estágio em UX Design',
    company: 'Aurora Produtos',
    initials: 'AP',
    location: 'Campinas, SP',
    mode: 'Híbrido',
    type: 'Estágio',
    area: 'Design',
    salary: 'R$ 1.700,00',
    benefits: ['Vale-refeição', 'Plano de saúde'],
    deadline: '20 de outubro',
    posted: 'Há 1 dia',
    summary: 'Participe de pesquisas e transforme aprendizados em experiências digitais melhores.',
    description: 'Você apoiará discovery, organização de evidências e prototipação de fluxos.',
    activities: ['Apoiar entrevistas.', 'Organizar insights.', 'Criar wireframes.'],
    required: ['Figma', 'Comunicação', 'Portfólio acadêmico'],
    desired: ['Pesquisa com usuários', 'Acessibilidade'],
    match: 64,
    matched: ['Figma', 'Comunicação'],
    gaps: ['Pesquisa com usuários']
  },
  {
    id: 'marketing-lume',
    title: 'Estágio em Marketing Digital',
    company: 'Lume Varejo',
    initials: 'LV',
    location: 'Rio de Janeiro, RJ',
    mode: 'Presencial',
    type: 'Estágio',
    area: 'Marketing',
    salary: 'R$ 1.500,00',
    benefits: ['Vale-transporte', 'Vale-refeição'],
    deadline: '24 de outubro',
    posted: 'Há 3 dias',
    summary: 'Apoie campanhas, conteúdos e leitura de resultados em canais digitais.',
    description: 'Uma oportunidade para aprender planejamento, execução e mensuração de campanhas.',
    activities: ['Organizar calendário.', 'Apoiar publicações.', 'Consolidar indicadores.'],
    required: ['Boa escrita', 'Organização', 'Redes sociais'],
    desired: ['Canva', 'Google Analytics'],
    match: 61,
    matched: ['Boa escrita', 'Organização'],
    gaps: ['Google Analytics']
  },
  {
    id: 'produto-vereda',
    title: 'Pessoa Desenvolvedora Júnior',
    company: 'Vereda Sistemas',
    initials: 'VS',
    location: 'Belo Horizonte, MG',
    mode: 'Remoto',
    type: 'Júnior',
    area: 'Tecnologia',
    salary: 'R$ 3.400,00',
    benefits: ['Plano de saúde', 'Auxílio home office'],
    deadline: '28 de outubro',
    posted: 'Há 4 dias',
    summary: 'Evolua produtos B2B com mentoria e boas práticas de engenharia.',
    description: 'Atuação em produto web com acompanhamento próximo do time.',
    activities: ['Implementar histórias.', 'Criar testes.', 'Participar de revisões.'],
    required: ['JavaScript', 'React', 'Git', 'APIs REST'],
    desired: ['TypeScript', 'Testes automatizados'],
    match: 76,
    matched: ['JavaScript', 'React', 'Git'],
    gaps: ['Testes automatizados']
  },
  {
    id: 'rh-pontes',
    title: 'Estágio em Pessoas e Cultura',
    company: 'Pontes Consultoria',
    initials: 'PC',
    location: 'Curitiba, PR',
    mode: 'Híbrido',
    type: 'Estágio',
    area: 'Recursos Humanos',
    salary: 'R$ 1.550,00',
    benefits: ['Vale-refeição', 'Auxílio-transporte'],
    deadline: '30 de outubro',
    posted: 'Há 2 dias',
    summary: 'Apoie experiências de entrada, desenvolvimento e comunicação com pessoas.',
    description: 'Você acompanhará processos de onboarding e ações de desenvolvimento.',
    activities: ['Organizar agendas.', 'Apoiar onboarding.', 'Atualizar indicadores.'],
    required: ['Organização', 'Comunicação', 'Pacote Office'],
    desired: ['Excel', 'Noções de recrutamento'],
    match: 55,
    matched: ['Organização', 'Comunicação'],
    gaps: ['Noções de recrutamento']
  }
]

export const candidates = [
  {
    id: 'marina-costa',
    name: 'Marina Costa',
    course: 'Análise e Desenvolvimento de Sistemas',
    semester: '3º semestre',
    location: 'São Paulo, SP',
    match: 70,
    stage: 'Nova candidatura',
    appliedAt: 'Hoje, 10:42',
    skills: ['HTML', 'CSS', 'JavaScript', 'Git']
  },
  {
    id: 'gabriel-lima',
    name: 'Gabriel Lima',
    course: 'Sistemas de Informação',
    semester: '4º semestre',
    location: 'Osasco, SP',
    match: 66,
    stage: 'Em análise',
    appliedAt: 'Ontem, 17:18',
    skills: ['JavaScript', 'Git', 'Figma']
  },
  {
    id: 'ana-ribeiro',
    name: 'Ana Ribeiro',
    course: 'Design Digital',
    semester: '5º semestre',
    location: 'São Paulo, SP',
    match: 62,
    stage: 'Entrevista',
    appliedAt: '21 set., 14:05',
    skills: ['Figma', 'HTML', 'Acessibilidade']
  }
]

export const plans = [
  {
    id: 'free',
    name: 'Grátis',
    price: 0,
    suffix: '',
    description: 'Para experimentar o fluxo básico.',
    features: ['1 vaga ativa', 'Visualização básica de candidatos', 'Atualizações por e-mail'],
    limits: ['Sem filtros avançados', 'Sem funil completo']
  },
  {
    id: 'start',
    name: 'Start',
    price: 29.9,
    suffix: '/mês',
    description: 'Para começar a recrutar com organização.',
    features: ['Até 3 vagas ativas', 'Filtros avançados', 'Funil básico de candidatos', 'Exportação em CSV'],
    limits: []
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 59.9,
    suffix: '/mês',
    description: 'Para processos recorrentes de seleção.',
    features: ['Mais vagas simultâneas', 'Funil completo', 'Compatibilidade explicável', 'Modelos de mensagem'],
    limits: []
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 99.9,
    suffix: '/mês',
    description: 'Para equipes com maior volume.',
    features: ['Vagas ilimitadas', 'Acesso para equipe', 'Relatórios', 'Suporte prioritário'],
    limits: []
  }
]

export const defaultState = {
  role: null,
  savedJobs: [],
  selectedJobId: 'frontend-horizonte',
  highlight: false,
  selectedPlanId: 'start',
  planActive: false,
  applicationSent: false,
  applicationMessage: 'Tenho interesse em aprender com o time e contribuir com minha experiência acadêmica em interfaces web.',
  company: {
    name: 'Empresa Horizonte',
    responsible: 'Rafael Mendes',
    email: 'talentos@empresahorizonte.com.br',
    segment: 'Tecnologia e serviços digitais',
    size: '51 a 200 pessoas'
  },
  student: {
    name: 'Marina Costa',
    email: 'marina.costa@email.com',
    course: 'Análise e Desenvolvimento de Sistemas',
    institution: 'Faculdade Nova Cidade',
    semester: '3º semestre',
    city: 'São Paulo, SP',
    workMode: 'Híbrido ou remoto',
    skills: 'HTML, CSS, JavaScript, React, Git, Figma',
    cvName: 'Curriculo-Marina-Costa.pdf'
  },
  jobDraft: {
    title: 'Estágio em Desenvolvimento Front-end',
    area: 'Tecnologia',
    location: 'São Paulo, SP',
    mode: 'Híbrido',
    type: 'Estágio',
    salary: 'R$ 1.800,00',
    benefits: 'Vale-refeição, auxílio-transporte e Gympass',
    deadline: '2026-10-12',
    description: 'Ajude a criar experiências digitais simples e acessíveis para milhares de pessoas.',
    required: 'HTML semântico\nCSS responsivo\nJavaScript básico\nGit\nDisponibilidade de 6 horas',
    desired: 'React\nFigma\nTestes de interface'
  }
}
